### ISSUE TITLE
Minor codebase issues

### ISSUE THREAD

**Issue by nrennie** [Stat-Cook/deident#17]
- Not a big issues at this point, but the codebase has a significant amount of commented out code that should be removed if not needed, or added to GitHub issues if you're saving it for later.
- `create_deident.R` docs: "list of variables to be deidentifier" -> "list of variables to be deidentified"
- Suggest removing the `TODO.R` file - use GitHub issues for To Do lists. At the very least add it to Rbuildignore.
- Add linting to code using lintr - especially for examples. Also suggest adding this as a GitHub Action. Easy to reformat existing code using {styler}.
- Changelog numbers don't match package version.

**Comment by Stat-Cook** [comment]
Tasks:

* ~~Not a big issues at this point, but the codebase has a significant amount of commented out code that should be removed if not needed, or added to GitHub issues if you're saving it for later.~~
* ~~create_deident.R docs: "list of variables to be deidentifier" -> "list of variables to be deidentified"~~
* ~~Suggest removing the TODO.R file - use GitHub issues for To Do lists. At the very least add it to Rbuildignore.~~
* ~~Add linting to code using lintr - especially for examples. Also suggest adding this as a GitHub Action. Easy to reformat existing code using {styler}.~~ Github action is now styling code on push.
* ~~Changelog numbers don't match package version.~~

**Comment by Stat-Cook** [comment]
@nrennie  For clarity - Changelog refers to NEWS containing a reference to 'deident 1.0' as opposed to the DESCRIPTION file which refers to 1.0.0?

**Comment by nrennie** [comment]
> @nrennie For clarity - Changelog refers to NEWS containing a reference to 'deident 1.0' as opposed to the DESCRIPTION file which refers to 1.0.0?

Yes, that's right
