### ISSUE TITLE
Add a code coverage badge

### ISSUE THREAD

**Issue by PatrickRWright** [Stat-Cook/deident#7]

**Comment by Stat-Cook** [comment]
Afraid we have no familiarity with badges - can you recommend a method that coincides with `covr`?

**Comment by PatrickRWright** [comment]
Have a look at the help here `?usethis::use_badge()`. Generally the `usethis` package will provide many boilerplate setups that will probably help you to "hit the ground running".

Its also possible to look at other popular packages to see how they set things up. e.g. https://github.com/tidyverse/tidyr

**Comment by Stat-Cook** [comment]
Ahh brilliant - `usethis::use_test` is definitely an old friend.

**Comment by Stat-Cook** [comment]
code coverage badge added - currently at 94%

**Comment by PatrickRWright** [comment]
@Stat-Cook looks like the badge is broken.
